name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64]
        include:
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: Build and package
        run: |
          EXT=""
          ARCHIVE_EXT="tar.gz"
          if [ "${{ matrix.goos }}" = "windows" ]; then
            EXT=".exe"
            ARCHIVE_EXT="zip"
          fi
          BINARY="tskoans${EXT}"
          ARCHIVE="tskoans-${{ matrix.goos }}-${{ matrix.goarch }}.${ARCHIVE_EXT}"
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} CGO_ENABLED=0 go build -o "$BINARY"
          if [ "${{ matrix.goos }}" = "windows" ]; then
            zip "$ARCHIVE" "$BINARY"
          else
            tar -czf "$ARCHIVE" "$BINARY"
          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.goos }}-${{ matrix.goarch }}
          path: |
            tskoans-*.tar.gz
            tskoans-*.zip

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: binaries-*
          path: .
      - name: Move archives to root
        run: |
          find . -type f -name "tskoans-*.tar.gz" -exec mv {} . \;
          find . -type f -name "tskoans-*.zip" -exec mv {} . \;
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "tskoans-*.tar.gz,tskoans-*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
