name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64]
        include:
          - goos: darwin
            goarch: arm64
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Build
        run: |
          FILENAME="tskoans-${{ matrix.goos }}-${{ matrix.goarch }}"
          if [ "${{ matrix.goos }}" = "windows" ]; then
            FILENAME="$FILENAME.exe"
          fi
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} CGO_ENABLED=0 go build -o "$FILENAME"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: tskoans-*
  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binaries
          path: .
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "tskoans-*"
          token: ${{ secrets.GITHUB_TOKEN }}
